= Intershop Commerce Management Component Gradle Plugin
:latestRevision: 1.0.0
:icons: font

Note: This plugin requires Gradle 4 and JDK 8

== Summary
This plugin creates all necessary artifacts of a component of Intershop Commerce Management.
It provides these as artifacts for https://docs.gradle.org/current/userguide/publishing_ivy.html[Ivy] or
https://docs.gradle.org/current/userguide/publishing_maven.html[Maven] publishing.

== Usage
To apply the ICM Component Gradle plugin to your project, add the following in your build script:

[source,groovy]
[subs=+attributes]
.build.gradle
----
plugins {
    id 'com.intershop.gradle.icm-component' version '{latestRevision}'
}
----

== Tasks
The ICM Component Gradle plugin adds ...

[cols="25%,30%,45%", width="90%, options="header"]
|===
|Task name                          | Type                              |Description
|===

== Project Extension 'intershop'
This plugin adds an extension *`intershop`* to the project.

=== Properties

[cols="25%,10%,10%,55%", width="90%, options="header"]
|===
|Property | Type | Default value | Description
|===

=== Methods
[cols="20%,15%,65%", width="90%", options="header"]
|===
|Method  | Values | Description
|===

== License

Copyright 2014-2018 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
